### ISSUE TITLE
Dark Oak and Acacia smelting into charcoal: extra conflicting recipe

### ISSUE THREAD

**Issue by Shahelion** [jadedcat/JadedTweaks#31]
I was playing last night and Acacia Logs smelted into 4 charcoal each, but today they only give one each. NEI shows the log-specific recipes, plus one for a single charcoal where the input changes between acacia and dark oak logs. No mods changed between yesterday and today, it seems to just have decided to use the other recipe.

Acacia recipe: https://gyazo.com/dbddbb70fbcba551f223823bfc677b8f

What I assume is the vanilla recipe: https://gyazo.com/804a3051111d0be70f66af8d96cf7e84

Also what Thaumcraft aspect does the mod add? I can't find anything for this.

**Comment by elifoster** [comment]
@jadedcat You should probably remove the old recipes when you create these new smelting recipes, otherwise we get weird results like in Esteemed-Innovation/Flaxbeards-Steam-Power#336.

**Comment by ghost** [comment]
This issue was moved to JadedPacks/JadedTweaks#2

**Comment by ghost** [comment]
This was fixed in upstream on JadedPacks/JadedTweaks, you may want to close this @Zsashas
